(define (problem p1)
	(:domain farmer)
	(:objects farmer - farmer owca wilk kapusta)
	(:init
		(moze_zjesc wilk owca)
		(moze_zjesc owca kapusta)
		(not (zachod farmer))
		(not (zachod owca))
		(not (zachod wilk))
		(not (zachod kaputsta))
	)
	(:goal
		(and
			(zachod farmer)
			(zachod owca)
			(zachod wilk)
			(zachod kapusta)			
		)
	)
)