; Wersja z wykorzystaniem typów zmiennych
(define (problem p1)
	(:domain hanoi)
	(:objects k5 k4 k3 k2 k1 - block x y z - pole)
	(:init
		(on-pole x k1)
		(on-pole x k2)
		(on-pole x k3)
		(on-pole x k4)
		(on-pole x k5)
		
		(smaller k5 x)
		(smaller k5 y)
		(smaller k5 z)
		(smaller k4 x)
		(smaller k4 y)
		(smaller k4 z)
		(smaller k3 x)
		(smaller k3 y)
		(smaller k3 z)
		(smaller k2 x)
		(smaller k2 y)
		(smaller k2 z)
		(smaller k1 x)
		(smaller k1 y)
		(smaller k1 z)
		
		(smaller k4 k5)
		(smaller k3 k5)
		(smaller k3 k4)
		(smaller k2 k5)
		(smaller k2 k4)
		(smaller k2 k3)
		(smaller k1 k5)
		(smaller k1 k4)
		(smaller k1 k3)
		(smaller k1 k2)
		
		(on-pole x k1)
		(on-pole x k2)
		(on-pole x k3)
		(on-pole x k4)
		(on-pole x k5)
		
		(clear y)
		(clear z)
		
		(on x k5)
		(on k5 k4)
		(on k4 k3)
		(on k3 k2)
		(on k2 k1)
		(clear k1)
	)
	(:goal
		(and
			(clear x)
			(clear y)
			(on z k5)
			(on k5 k4)
			(on k4 k3)
			(on k3 k2)
			(on k2 k1)
			(clear k1)
			(on-pole z k1)
			(on-pole z k2)
			(on-pole z k3)
			(on-pole z k4)
			(on-pole z k5)			
		)
	)
)